apiVersion: v1 
kind: Service 
metadata:
  name: clusterip-service 
  namespace: roboshop
spec:
  type: ClusterIP
  selector:           # Matches the label on the Pod above
    app: service
    type: clusterip 
  ports:
  - protocol: TCP 
    port: 8080            # Internal access port for other pods and 80 u can access directtly curl <service name> but if u give 8080 curl <service name>:8080
    targetPort: 80      # Target port inside the container 
---
apiVersion: v1 
kind: Pod 
metadata:
  name: clusterip-pod
  namespace: roboshop
  labels: 
    app: service 
    type: clusterip 
spec:
  containers:
  - name: clusterip-cont 
    image: nginx:mainline-alpine3.24-perl
    ports:
    - containerPort: 80

