apiVersion: v1
kind: PersistentVolume              #not a namespace level cluster level
metadata:
  name: ebc-static-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b7124f606f06f4df                     #manually created ebs volume id 
---
apiVersion: v1 
kind: PersistentVolumeClaim     #namespace scoped 
metadata:
  name: ebc-static-pvc 
  namespace: roboshop
spec:
  storageClassName:
  volumeName: ebc-static-pv
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: Pod 
metadata:
  name: ebs-static-pod 
  namespace: roboshop
  labels:
    app: ebs-pod 
    type: ebs 
spec:
  containers:
  - name: nginx-ebs-static-cont
    image: nginx:mainline-alpine3.24-perl
    ports:
    - containerPort: 80
    volumeMounts:
    - name: ebs-static-nginx-vol 
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1a
  volumes: 
  - name: ebs-static-nginx-vol 
    persistentVolumeClaim:
      claimName: ebc-static-pvc 
---
apiVersion: v1 
kind: Service
metadata: 
  name: ebs-static-service 
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: ebs-pod 
    type: ebs
  ports:
  - protocol: TCP 
    port: 80          #service-port
    targetPort: 80        #container-port