apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc 
  namespace: roboshop
spec:
  storageClassName: "ebs-dynamic-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1 
kind: Pod 
metadata:
  name: ebs-dynamic-pod 
  namespace: roboshop
  labels:
    app: ebs-dynamic
    type: dynamic
spec:
  containers:
  - name: nginx
    image: nginx 
    ports:
    - containerPort: 80 
    volumeMounts:
    - name: ebs-dynamic-vol             #volume name 
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic-vol
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc 

---
apiVersion: v1 
kind: Service 
metadata:
  name: ebs-dynamic-service  
  namespace: roboshop
spec:
  type: LoadBalancer 
  selector:
    app: ebs-dynamic
    type: dynamic
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
