apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: efs-static-pv 
spec:
  accessModes:
  - ReadWriteMany 
  volumeMode: Filesystem
  capacity:
    storage: 10Gi        # EFS expands automatically; this is a placeholder
  storageClassName: "" 
  persistentVolumeReclaimPolicy: Retain
  csi:  
    driver: efs.csi.aws.com
    volumeHandle: fs-067a21efaabaf2b82
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: efs-static-pvc 
  namespace: roboshop 
spec:
  storageClassName: "" 
  accessModes:
  - ReadWriteMany
  volumeName: efs-static-pv 
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: efs-static-pod 
  namespace: roboshop
  labels: 
    app: efs-pod
    type: efs-static
spec:
  containers:
  - name: efs-static-cont 
    image: nginx 
    volumeMounts:
    - name: efs-static-vol
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a    
  volumes: 
  - name: efs-static-vol 
    persistentVolumeClaim: 
        claimName: efs-static-pvc
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: efs-static-service 
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: efs-pod
    type: efs-static
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 