apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: efs-dynamic-pvc 
  namespace: roboshop 
spec:
  storageClassName: efs-dynamic
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: efs-dynamic-pod 
  namespace: roboshop
  labels: 
    app: efs-pod
    type: efs-dynamic
spec:
  containers:
  - name: efs-dynamic-cont 
    image: nginx 
    volumeMounts:
    - name: efs-dynamic-vol
      mountPath: /usr/share/nginx/html  
  volumes: 
  - name: efs-dynamic-vol 
    persistentVolumeClaim: 
        claimName: efs-dynamic-pvc
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: efs-dynamic-service 
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: efs-pod
    type: efs-dynamic
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 