apiVersion: v1 
kind: Deployment
metadata:
  name: nginx-deployment 
  namespace: roboshop 
  labels: 
    app: nginx-deployment-level 
    type: chart 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx      
      type: chart
  template:
    metadata:
      labels: 
        app: nginx 
        type: chart
    spec:
      containers:
      - name: nginx-cont 
        image: {{ .Values.image.name }} 
        ports:
        - containerPort: {{ .Values.port.containerPort }}
