apiVersion: v1 
kind: Pod       #Pod  declaration should be same if u give pod u will get error
metadata:
  name: roboshop-pod      #this is pod name
  namespace: roboshop
spec: 
  containers:
  - name: nginx-container     #this is container name 
    image: nginx
    ports:
    - containerPort: 80 
    
  
  