apiVersion: v1 
kind: Pod 
metadata: 
  name: multi-container-pod 
  namespace: roboshop
spec:
  containers:
  - name: nginx-container 
    image: nginx
    ports:
      containerPort: 80 
  - name: almalinux-cont     #side-car container 
    image: almalinux:8
    command: [ "echo", "this is sidecar container"]