apiVersion: v1 
kind: Pod
metadata:
  name: annotations-pod 
  namespace: roboshop
spec:
  containers:
  - name: nginx-container
    image: nginx 
    ports:
    - containerPort: 80
    env:
    - name: DB_HOST
      value: mongodb
    - name: DB_PORT
      value: "27017"
    - name: APP_ENV
      value: production
