apiVersion: v1 
kind: Pod 
metadata: 
  name: requstandlimit-pod 
  namespace: roboshop
spec:
  containers:
  - name: requstandlimit-container 
    image: nginx:mainline-alpine3.24-perl
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
