apiVersion: v1 
kind: Secret 
metadata: 
  name: secret-resource 
  namespace: roboshop
type: Opaque
data:
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: QWRtaW5AMTIz
---
apiVersion: v1 
kind: Pod 
me-podadata:
  name: secret 
  namespace: roboshop
spec: 
  containers:
  - name: secret-container 
    image: nginx:mainline-alpine3.24-perl
    ports:
    - containerPort: 80
    # env:
    # - name: secretname 
    #   valueFrom:
    #     secretKeyRef:
    #     - name: secret-resource
    #       key: DB_USERNAME
    # - name: secretname 
    #   valueFrom:
    #     secretKeyRef:
    #     - name: secret-resource
    #       key: DB_PASSWORD
    # envFrom:
    # - secretRef:
    #     name: secret-resource 

#using volumes 
    volumeMounts:
    - name: secret-vol 
      mountPath: /etc/secrets 
      readOnly: true
  
  volumes:
  - name: secret-vol 
    secret:
      secretName: secret-resource 
